// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jaywwnayqiuobifrrqnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpheXd3bmF5cWl1b2JpZnJycW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0MjIzOTIsImV4cCI6MjA1Mzk5ODM5Mn0.XNRSpuWGg7rR-XzWVspdsiEqfX2OXENU_9LQEsjzYx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);